#ifndef WEB_SERVER_HTML_H
#define WEB_SERVER_HTML_H

const char* config_page_html =
"<!DOCTYPE HTML><html><head>"
"<title>ESP32 Roller Blind Config</title>"
"<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">"
"<style>"
"  body { font-family: Arial, sans-serif; background-color: #f4f4f4; margin: 0; padding: 20px; }"
"  .container { max-width: 600px; margin: auto; background: #fff; padding: 20px; border-radius: 8px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }"
"  h2 { color: #333; }"
"  .form-group { margin-bottom: 15px; }"
"  label { display: block; margin-bottom: 5px; font-weight: bold; }"
"  input[type='text'], input[type='password'], select {"
"    width: 100%; padding: 10px; border: 1px solid #ddd; border-radius: 4px; box-sizing: border-box;"
"  }"
"  button, input[type='submit'] {"
"    width: 100%; background-color: #4CAF50; color: white; padding: 10px 20px; border: none;"
"    border-radius: 4px; cursor: pointer; font-size: 16px; box-sizing: border-box;"
"  }"
"  button:hover, input[type='submit']:hover { background-color: #45a049; }"
"  .footer { text-align: center; margin-top: 20px; color: #777; }"
"</style>"
"<script>"
"function scanWifi() {"
"    console.log('Scanning for Wi-Fi networks...');"
"    const scanButton = document.getElementById('scan_button');"
"    scanButton.innerText = 'Scanning...';"
"    scanButton.disabled = true;"
"    fetch('/api/scanwifi')"
"        .then(response => response.json())"
"        .then(data => {"
"            const ssidSelect = document.getElementById('ssid_select');"
"            ssidSelect.innerHTML = '<option value=\"\">Select a Network</option>';"
"            data.forEach(net => {"
"                let option = new Option(net.ssid + ' (' + net.rssi + ')', net.ssid);"
"                ssidSelect.add(option);"
"            });"
"            scanButton.innerText = 'Scan Complete';"
"            document.getElementById('ssid_select_group').style.display = 'block';"
"            setTimeout(() => { scanButton.innerText = 'Scan Again'; scanButton.disabled = false; }, 2000);"
"        })"
"        .catch(error => {"
"            console.error('Error scanning for Wi-Fi:', error);"
"            scanButton.innerText = 'Scan Failed';"
"            setTimeout(() => { scanButton.innerText = 'Scan Again'; scanButton.disabled = false; }, 2000);"
"        });"
"}"
"function selectSsid() {"
"    const selectedSsid = document.getElementById('ssid_select').value;"
"    if (selectedSsid) {"
"        document.getElementById('ssid_input').value = selectedSsid;"
"    }"
"}"
"</script>"
"</head><body>"
"<div class='container'>"
"  <h2>Wi-Fi Configuration</h2>"
"  <form method='post' action='/save'>"
"    <div class='form-group'>"
"        <label>Scan for Networks</label>"
"        <button type='button' id='scan_button' onclick='scanWifi()'>Scan</button>"
"    </div>"
"    <div class='form-group' id='ssid_select_group' style='display:none;'>"
"      <label for='ssid_select'>Available Networks</label>"
"      <select id='ssid_select' onchange='selectSsid()'><option value=''>Scan first</option></select>"
"    </div>"
"    <div class='form-group'>"
"      <label for='ssid_input'>SSID</label>"
"      <input type='text' id='ssid_input' name='ssid' required>"
"    </div>"
"    <div class='form-group'>"
"      <label for='pass'>Password</label>"
"      <input type='password' id='pass' name='pass'>"
"    </div>"
"    <h2>MQTT Configuration</h2>"
"    <div class='form-group'>"
"      <label for='mqtt_server'>Server IP</label>"
"      <input type='text' id='mqtt_server' name='mqtt_server'>"
"    </div>"
"    <div class='form-group'>"
"      <label for='mqtt_port'>Port</label>"
"      <input type='text' id='mqtt_port' name='mqtt_port' value='1883'>"
"    </div>"
"    <div class='form-group'>"
"      <label for='mqtt_user'>Username</label>"
"      <input type='text' id='mqtt_user' name='mqtt_user'>"
"    </div>"
"    <div class='form-group'>"
"      <label for='mqtt_pass'>Password</label>"
"      <input type='password' id='mqtt_pass' name='mqtt_pass'>"
"    </div>"
"    <div class='form-group'>"
"      <label for='mqtt_base_topic'>MQTT Base Topic</label>"
"      <input type='text' id='mqtt_base_topic' name='mqtt_base_topic' value='blinds/living_room' placeholder='e.g., blinds/living_room'>"
"    </div>"
"    <input type='submit' value='Save and Reboot'>"
"  </form>"
"  <div class='footer'>"
"    <p>ESP32 Roller Blind Controller</p>"
"  </div>"
"</div>"
"</body></html>";

#endif // WEB_SERVER_HTML_H
